[workspace]
members = [
    "testchain/node",
    "testchain/runtime",
    "primitives",
    "rpc",
    "pallets/spacewalk",
    "pallets/stellar-relay",
    "pallets/fee",
    "pallets/reward",
    "pallets/staking",
    "pallets/reward"
]
[profile.release]
panic = "unwind"
