[workspace]
members = [
    "pallets/currency",
    "pallets/fee",
    "pallets/nomination",
    "pallets/oracle",
    "pallets/reward",
    "pallets/spacewalk",
    "pallets/staking",
    "pallets/stellar-relay",
    "pallets/vault-registry",
    "primitives",
    "rpc",
    "testchain/node",
    "testchain/runtime",
]
[profile.release]
panic = "unwind"
